
path_pats = []

path_pats.append(('/'                                                  , 'the rest',          'the rest',         ))
path_pats.append(('multiple'                                           , 'the rest',          'the rest',         ))
path_pats.append(('/predecessor_block_metadata_hash'                   , 'the rest',          'the rest',         ))
path_pats.append(('/predecessor_ops_metadata_hash'                     , 'the rest',          'the rest',         ))
path_pats.append(('/protocol'                                          , 'the rest',          'the rest',         ))
path_pats.append(('/data'                                              , 'the rest',          'the rest',         ))

path_pats.append(('/data/big_maps'                                     , 'the rest',           'the rest', ))
path_pats.append(('/data/big_maps/index'                               , '/data/big_maps/**/*',  'the rest', ))
path_pats.append(('/data/big_maps/index/*'                             , '/data/big_maps/**/*',  'the rest', ))
path_pats.append(('/data/big_maps/index/*/contents'                    , '/data/big_maps/**/*',  '/data/big_maps/index/*/contents'        , ))
path_pats.append(('/data/big_maps/index/*/contents/*'                  , '/data/big_maps/**/*',  '/data/big_maps/index/*/contents/*'      , ))
path_pats.append(('/data/big_maps/index/*/contents/*/data'             , '/data/big_maps/**/*',  '/data/big_maps/index/*/contents/*/data' , ))
path_pats.append(('/data/big_maps/index/*/key_type'                    , '/data/big_maps/**/*',  'the rest', ))
path_pats.append(('/data/big_maps/index/*/total_bytes'                 , '/data/big_maps/**/*',  'the rest', ))
path_pats.append(('/data/big_maps/index/*/value_type'                  , '/data/big_maps/**/*',  'the rest', ))
path_pats.append(('/data/big_maps/next'                                , '/data/big_maps/**/*',  'the rest', ))

path_pats.append(('/data/contracts'                                    , 'the rest',           'the rest' ))
path_pats.append(('/data/contracts/global_counter'                     , '/data/contracts/**/*', 'the rest' ))
path_pats.append(('/data/contracts/index'                              , '/data/contracts/**/*', '/data/contracts/index'           ))
path_pats.append(('/data/contracts/index/*'                            , '/data/contracts/**/*', '/data/contracts/index/*'         ))
path_pats.append(('/data/contracts/index/*/balance'                    , '/data/contracts/**/*', '/data/contracts/index/*/<the rest>' ))
path_pats.append(('/data/contracts/index/*/change'                     , '/data/contracts/**/*', '/data/contracts/index/*/<the rest>' ))
path_pats.append(('/data/contracts/index/*/counter'                    , '/data/contracts/**/*', '/data/contracts/index/*/<the rest>' ))
path_pats.append(('/data/contracts/index/*/data'                       , '/data/contracts/**/*', '/data/contracts/index/*/<the rest>' ))
path_pats.append(('/data/contracts/index/*/data/code'                  , '/data/contracts/**/*', '/data/contracts/index/*/<the rest>' ))
path_pats.append(('/data/contracts/index/*/data/storage'               , '/data/contracts/**/*', '/data/contracts/index/*/<the rest>' ))
path_pats.append(('/data/contracts/index/*/delegate'                   , '/data/contracts/**/*', '/data/contracts/index/*/<the rest>' ))
path_pats.append(('/data/contracts/index/*/delegated'                  , '/data/contracts/**/*', '/data/contracts/index/*/<the rest>' ))
path_pats.append(('/data/contracts/index/*/frozen_balance'             , '/data/contracts/**/*', '/data/contracts/index/*/<the rest>' ))
path_pats.append(('/data/contracts/index/*/frozen_balance/*'           , '/data/contracts/**/*', '/data/contracts/index/*/<the rest>' ))
path_pats.append(('/data/contracts/index/*/frozen_balance/*/deposits'  , '/data/contracts/**/*', '/data/contracts/index/*/<the rest>' ))
path_pats.append(('/data/contracts/index/*/frozen_balance/*/fees'      , '/data/contracts/**/*', '/data/contracts/index/*/<the rest>' ))
path_pats.append(('/data/contracts/index/*/frozen_balance/*/rewards'   , '/data/contracts/**/*', '/data/contracts/index/*/<the rest>' ))
path_pats.append(('/data/contracts/index/*/len'                        , '/data/contracts/**/*', '/data/contracts/index/*/<the rest>' ))
path_pats.append(('/data/contracts/index/*/manager'                    , '/data/contracts/**/*', '/data/contracts/index/*/manager' ))
path_pats.append(('/data/contracts/index/*/paid_bytes'                 , '/data/contracts/**/*', '/data/contracts/index/*/<the rest>' ))
path_pats.append(('/data/contracts/index/*/roll_list'                  , '/data/contracts/**/*', '/data/contracts/index/*/<the rest>' ))
path_pats.append(('/data/contracts/index/*/used_bytes'                 , '/data/contracts/**/*', '/data/contracts/index/*/<the rest>' ))

path_pats.append(('/data/rolls'                                        , 'the rest',           'the rest',    ))
path_pats.append(('/data/rolls/index'                                  , '/data/rolls/**/*',     'the rest',    ))
path_pats.append(('/data/rolls/index/*'                                , '/data/rolls/**/*',     'the rest',    ))
path_pats.append(('/data/rolls/index/*/successor'                      , '/data/rolls/**/*',     'the rest',    ))
path_pats.append(('/data/rolls/limbo'                                  , '/data/rolls/**/*',     'the rest',    ))
path_pats.append(('/data/rolls/owner'                                  , '/data/rolls/**/*',     'the rest',    ))
path_pats.append(('/data/rolls/owner/current'                          , '/data/rolls/**/*',     'the rest',    ))
path_pats.append(('/data/rolls/owner/current/*'                        , '/data/rolls/**/*',     'the rest',    ))
path_pats.append(('/data/rolls/owner/snapshot'                         , '/data/rolls/**/*',     'the rest',    ))
path_pats.append(('/data/rolls/owner/snapshot/*'                       , '/data/rolls/**/*',     'the rest',    ))
path_pats.append(('/data/rolls/owner/snapshot/*/*'                     , '/data/rolls/**/*',     'the rest',    ))
path_pats.append(('/data/rolls/owner/snapshot/*/*/*'                   , '/data/rolls/**/*',     'the rest',    ))

path_pats.append(('/data/active_delegates_with_rolls'                  , 'the rest',          'the rest',         ))
path_pats.append(('/data/active_delegates_with_rolls/ed25519'          , 'the rest',          'the rest',         ))
path_pats.append(('/data/active_delegates_with_rolls/p256'             , 'the rest',          'the rest',         ))
path_pats.append(('/data/active_delegates_with_rolls/secp256k1'        , 'the rest',          'the rest',         ))
path_pats.append(('/data/cache'                                        , 'the rest',          'the rest',         ))
path_pats.append(('/data/cache/*'                                      , 'the rest',          'the rest',         ))
path_pats.append(('/data/cache/*/limit'                                , 'the rest',          'the rest',         ))
path_pats.append(('/data/commitments'                                  , 'the rest',          'the rest',         ))
path_pats.append(('/data/commitments/*'                                , 'the rest',          'the rest',         ))
path_pats.append(('/data/cycle'                                        , 'the rest',          'the rest',         ))
path_pats.append(('/data/cycle/*'                                      , 'the rest',          'the rest',         ))
path_pats.append(('/data/cycle/*/last_roll'                            , 'the rest',          'the rest',         ))
path_pats.append(('/data/cycle/*/nonces'                               , 'the rest',          'the rest',         ))
path_pats.append(('/data/cycle/*/nonces/*'                             , 'the rest',          'the rest',         ))
path_pats.append(('/data/cycle/*/random_seed'                          , 'the rest',          'the rest',         ))
path_pats.append(('/data/delegates'                                    , 'the rest',          'the rest',         ))
path_pats.append(('/data/delegates/ed25519'                            , 'the rest',          'the rest',         ))
path_pats.append(('/data/delegates/p256'                               , 'the rest',          'the rest',         ))
path_pats.append(('/data/delegates/secp256k1'                          , 'the rest',          'the rest',         ))
path_pats.append(('/data/delegates_with_frozen_balance'                , 'the rest',          'the rest',         ))
path_pats.append(('/data/delegates_with_frozen_balance/*'              , 'the rest',          'the rest',         ))
path_pats.append(('/data/delegates_with_frozen_balance/*/ed25519'      , 'the rest',          'the rest',         ))
path_pats.append(('/data/delegates_with_frozen_balance/*/p256'         , 'the rest',          'the rest',         ))
path_pats.append(('/data/delegates_with_frozen_balance/*/secp256k1'    , 'the rest',          'the rest',         ))
path_pats.append(('/data/domain'                                       , 'the rest',          'the rest',         ))
path_pats.append(('/data/liquidity_baking_cpmm_address'                , 'the rest',          'the rest',         ))
path_pats.append(('/data/liquidity_baking_escape_ema'                  , 'the rest',          'the rest',         ))
path_pats.append(('/data/sapling/index'                                , 'the rest',          'the rest',         ))
path_pats.append(('/data/sapling/index/*'                              , 'the rest',          'the rest',         ))
path_pats.append(('/data/sapling/index/*/\\d+'                         , 'the rest',          'the rest',         ))
path_pats.append(('/data/sapling/index/*/\\d+/ciphertexts'             , 'the rest',          'the rest',         ))
path_pats.append(('/data/sapling/index/*/\\d+/ciphertexts/*'           , 'the rest',          'the rest',         ))
path_pats.append(('/data/sapling/index/*/\\d+/ciphertexts/*/data'      , 'the rest',          'the rest',         ))
path_pats.append(('/data/sapling/index/*/\\d+/commitments'             , 'the rest',          'the rest',         ))
path_pats.append(('/data/sapling/index/*/\\d+/commitments/*'           , 'the rest',          'the rest',         ))
path_pats.append(('/data/sapling/index/*/\\d+/commitments/*/data'      , 'the rest',          'the rest',         ))
path_pats.append(('/data/sapling/index/*/\\d+/commitments_size'        , 'the rest',          'the rest',         ))
path_pats.append(('/data/sapling/index/*/\\d+/nullifiers_hashed'       , 'the rest',          'the rest',         ))
path_pats.append(('/data/sapling/index/*/\\d+/nullifiers_hashed/*'     , 'the rest',          'the rest',         ))
path_pats.append(('/data/sapling/index/*/\\d+/nullifiers_hashed/*/data', 'the rest',          'the rest',         ))
path_pats.append(('/data/sapling/index/*/\\d+/nullifiers_ordered'      , 'the rest',          'the rest',         ))
path_pats.append(('/data/sapling/index/*/\\d+/nullifiers_ordered/*'    , 'the rest',          'the rest',         ))
path_pats.append(('/data/sapling/index/*/\\d+/nullifiers_size'         , 'the rest',          'the rest',         ))
path_pats.append(('/data/sapling/index/*/\\d+/roots'                   , 'the rest',          'the rest',         ))
path_pats.append(('/data/sapling/index/*/\\d+/roots/*'                 , 'the rest',          'the rest',         ))
path_pats.append(('/data/sapling/index/*/\\d+/roots_level'             , 'the rest',          'the rest',         ))
path_pats.append(('/data/sapling/index/*/\\d+/total_bytes'             , 'the rest',          'the rest',         ))
path_pats.append(('/data/v1'                                           , 'the rest',          'the rest',         ))
path_pats.append(('/data/v1/constants'                                 , 'the rest',          'the rest',         ))
path_pats.append(('/data/v1/cycle_eras'                                , 'the rest',          'the rest',         ))
path_pats.append(('/data/version'                                      , 'the rest',          'the rest',         ))
path_pats.append(('/data/votes'                                        , 'the rest',          'the rest',         ))
path_pats.append(('/data/votes/ballots'                                , 'the rest',          'the rest',         ))
path_pats.append(('/data/votes/ballots/ed25519'                        , 'the rest',          'the rest',         ))
path_pats.append(('/data/votes/ballots/p256'                           , 'the rest',          'the rest',         ))
path_pats.append(('/data/votes/current_period'                         , 'the rest',          'the rest',         ))
path_pats.append(('/data/votes/current_proposal'                       , 'the rest',          'the rest',         ))
path_pats.append(('/data/votes/listings'                               , 'the rest',          'the rest',         ))
path_pats.append(('/data/votes/listings/ed25519'                       , 'the rest',          'the rest',         ))
path_pats.append(('/data/votes/listings/p256'                          , 'the rest',          'the rest',         ))
path_pats.append(('/data/votes/listings/secp256k1'                     , 'the rest',          'the rest',         ))
path_pats.append(('/data/votes/proposals'                              , 'the rest',          'the rest',         ))
path_pats.append(('/data/votes/proposals/*'                            , 'the rest',          'the rest',         ))
path_pats.append(('/data/votes/proposals/*/ed25519'                    , 'the rest',          'the rest',         ))
path_pats.append(('/data/votes/proposals/*/p256'                       , 'the rest',          'the rest',         ))
path_pats.append(('/data/votes/proposals/*/secp256k1'                  , 'the rest',          'the rest',         ))
path_pats.append(('/data/votes/proposals_count'                        , 'the rest',          'the rest',         ))
path_pats.append(('/data/votes/proposals_count/ed25519'                , 'the rest',          'the rest',         ))
path_pats.append(('/data/votes/proposals_count/p256'                   , 'the rest',          'the rest',         ))
path_pats.append(('/data/votes/proposals_count/secp256k1'              , 'the rest',          'the rest',         ))

path_pats = {
    k: (v,w)
    for (k, v, w) in path_pats
}
